project:
  type: website
  output-dir: docs

website:
  title: "Midwest Tour 2025"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: simplex
    css: styles.css

editor: source

